-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS api_practice_schema.applications
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    salary integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    CONSTRAINT applications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS api_practice_schema.drug_searches
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_name character varying COLLATE pg_catalog."default" NOT NULL,
    suspect_cause character varying COLLATE pg_catalog."default" NOT NULL,
    effect character varying COLLATE pg_catalog."default" NOT NULL,
    severity character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT drug_searches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS api_practice_schema.webhook_events
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    event_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT webhook_events_pkey PRIMARY KEY (id),
    CONSTRAINT webhook_events_event_id_key UNIQUE (event_id)
);
END;